orbs:
  aws-ecr: circleci/aws-ecr@3.1.0
version: 2.1

workflows:
  build_and_push_image:
    jobs:
      - aws-ecr/build_and_push_image:
          account-url: "${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com"
          repo: infra-demo
          region: ${AWS_DEFAULT_REGION}
          tag: "hello-${CIRCLE_SHA1}"
