version: 2
jobs:
  build:
    docker:
      - image: golang:1.12.1-stretch   # (1)
    working_directory: /go/src/github.com/CircleCI-Public/circleci-demo-docker
    steps:
      - checkout
      # ... steps for building/testing app ...

      - setup_remote_docker:   # (2)
          docker_layer_caching: true # (3)

      # Use a primary image that already has Docker (recommended)
      # or install it during a build like we do here
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.03.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin

      # Build and push Docker image.
      - run: |
          # Image tag, eg "02-04-2019-153701-a402c7a".
          TAG=`date +%d-%m-%Y-%H%M%S`-$CIRCLE_SHA1
          docker build -t   olitheolix/demowebapp:$TAG .
          docker login -u olitheolix -p $DOCKER_PASS
          docker push CircleCI-Public/circleci-demo-docker:$TAG
